// <auto-generated />
using System;
using JKKNIUBusBookingSystem.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JKKNIUBusBookingSystem.Migrations
{
    [DbContext(typeof(JKKNIUBusBookingSystemDbContext))]
    partial class JKKNIUBusBookingSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JKKNIUBusBookingSystem.Entites.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfExtraSeats")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRowInCenter")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeatsInCenterRight")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeatsInCenterleft")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeatsInLastSeries")
                        .HasColumnType("int");

                    b.Property<int>("deckerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("JKKNIUBusBookingSystem.Entites.ScheduleBus", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartingAt")
                        .HasColumnType("time");

                    b.Property<string>("StartingPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("theTownBusIsNow")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.ToTable("ScheduleBuses");
                });

            modelBuilder.Entity("JKKNIUBusBookingSystem.Entites.ScheduleBusSeats", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BookedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId", "SeatName");

                    b.ToTable("ScheduleBusSeats");
                });

            modelBuilder.Entity("JKKNIUBusBookingSystem.Entites.Student", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
